config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/auth', to: 'openid#auth', as: 'openid_auth'
  get '/openid_auth_callback', to: 'openid#auth_callback', as: 'openid_auth_callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Nonce

  protect_from_forgery prepend: true

  rescue_from(
    Rack::OAuth2::Client::Error,
    OpenIDConnect::Exception,
    Nonce::Exception,
    MultiJson::LoadError,
    OpenSSL::SSL::SSLError
  ) do |e|
    flash[:error] = if e.message.length > 2000
      'Unknown Error'
    else
      e.message
    end
    
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/openid_controller.rb
class OpenidController < ApplicationController

  def auth
  	# Redirect to provider's authentication page
  	redirect_to client.authorization_uri(
      response_type: :code,
      state: new_nonce,
      nonce: new_nonce,
      scope: [:openid, :email, :profile, :address].collect(&:to_s)
    )
  end

  # callback methods after OpenID authentcation
  def auth_callback
  	@response = params
  	client.redirect_uri = openid_auth_callback_url
    client.authorization_code = params['code']

    @access_token = client.access_token! client_auth_method: client_auth_method
    @userinfo = @access_token.userinfo!

    @id_token = decode_id @access_token.id_token
    @id_token.verify!(
      issuer: ENV['OPENID_ISSUER'],
      client_id: ENV['OPENID_CLIENT_ID'],
      nonce: stored_nonce
    )
    @openid_subject = @id_token.subject
  end

  protected

  def options
    {
      identifier: ENV['OPENID_CLIENT_ID'],
      secret: ENV['OPENID_CLIENT_SECRET'],
      scopes_supported: [:openid, :email, :profile, :address],
      host: ENV['OPENID_PROVIDER_URL'],
      port: ENV['OPENID_PORT'] || 443,
      scheme: 'https',
      jwks_uri:openid_config.jwks_uri,
      authorization_endpoint: openid_config.authorization_endpoint,
      token_endpoint: openid_config.token_endpoint,
      userinfo_endpoint: openid_config.userinfo_endpoint,
      redirect_uri: openid_auth_callback_url
    }
  end

  def openid_config
    @openid_config ||= OpenIDConnect::Discovery::Provider::Config.discover! ENV['OPENID_ISSUER']
  end

  def client
    @client ||= OpenIDConnect::Client.new options
  end

  def client_auth_method
    supported = openid_config.token_endpoint_auth_methods_supported
    if supported.present? && !supported.include?('client_secret_post')
      :post
    else
      :basic
    end
  end

  def decode_id(id_token)
    OpenIDConnect::ResponseObject::IdToken.decode id_token, openid_config.jwks
  end

  def to_access_token(access_token)
    OpenIDConnect::AccessToken.new(
      access_token: access_token,
      client: client
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container mt-300">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
      <%= link_to "<i class='fas fa-fingerprint'></i> Login with FIDO UAF and OpenID Connect".html_safe, openid_auth_path, class: "btn btn-primary btn-lg" %>
      <hr>
      <a class="login-links left" href="">Mobile App</a>
      <a class="login-links right" href="">Privacy Policy</a>
      <a class="login-links right" href="">Terms</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Ultra Auth FIDO UAF - Biometric Auth</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/x-icon' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<% if flash[:error].present? %>
  <article>
    <h3>Errors</h3>
    <pre><p><%= flash[:error] %></p></pre>
  </article>
<% end %>

<%= yield %>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>